Pytest:
  script:
    - SFILE=/storage/singularity/custom_environment/ywatanabe/rapids_torch_tensorflow_20211025.sif
    - export SINGULARITY_BINDPATH=/storage,/work
    - export SINGULARITYENV_HOSTNAME=$HOSTNAME
    - export SINGULARITYENV_PYTHONPATH="./src"
    - singularity exec --nv --cleanenv $SFILE python -m pytest test
  allow_failure: true
  tags:
    - engine-g
